### ISSUE TITLE
TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by avargaskun** [Microsoft/vscode-cordova#232]
Running on OSX 10.12.2 with Code version 1.8.1 and Cordova Tools version 1.2.5 I get the following stack trace on the extensions output when trying to: "Attach to running iOS on simulator":

```
TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:73:16)
    at Function.Hash.hashCode (/Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/utils/hash.js:14:14)
    at new ExtensionMessageSender (/Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/common/extensionMessaging.js:25:33)
    at new ExtensionTelemetryReporter (/Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/utils/telemetry.js:291:43)
    at Function.TelemetryUtils.init (/Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/utils/telemetry.js:146:38)
    at Object.init (/Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/utils/telemetry.js:76:35)
    at CordovaDebugAdapter.initializeTelemetry (/Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/debugger/cordovaDebugAdapter.js:813:42)
    at /Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/debugger/cordovaDebugAdapter.js:95:70
    at CordovaDebugAdapter.attach (/Users/antonio/.vscode/extensions/vsmobile.cordova-tools-1.2.5/out/src/debugger/cordovaDebugAdapter.js:95:16)
```

I've tried disabling telemetry in ~/.vscode-cordova since it seems related given the stack trace but it did not help. Any ideas?

**Comment by MSLaguana** [comment]
Looks like this would happen if there is no `cwd` property in the launch.json entry that you are using. Have you modified your launch.json?

**Comment by vladimir-kotikov** [comment]
Closing due to lack of response. @avargaskun, please reopen in case if you still experiencing the problem.
