### ISSUE TITLE
Variable completion on debug annoing error

### ISSUE THREAD

**Issue by airstep** [Microsoft/vscode-cordova#278]
`
Error processing "completions": TypeError: Cannot read property 'length' of undefined
    at trimProperty (/home/taras/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:167:18)
    at propertyPreviewToString (/home/taras/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:161:19)
    at props.map.prop (/home/taras/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:43)
    at Array.map (native)
    at getObjectPreview (/home/taras/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:14)`

**Comment by annayafi** [comment]
Got this too:
```
Error processing "variables": TypeError: Cannot read property 'length' of undefined
    at trimProperty (C:\Users\Ma\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:167:18)
```

**Comment by p595285902** [comment]
I also have this problem, 
My device is Android Version:5.0.2

```
Error processing "variables": TypeError: Cannot read property 'length' of undefined
    at trimProperty (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:167:18)
    at propertyPreviewToString (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:161:19)
    at props.map.prop (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:151:43)
    at Array.map (native)
    at getObjectPreview (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:151:14)
    at Object.getRemoteObjectPreview (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:194:17)
    at CordovaDebugAdapter.createObjectVariable (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1359:33)
    at CordovaDebugAdapter.remoteObjectToVariable (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1302:33)
    at CordovaDebugAdapter.internalPropertyDescriptorToVariable (C:\Users\Wu\.vscode\extensions\vsmobile.cordova-tools-1.2.7\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdap[...]
```

**Comment by p595285902** [comment]
Found the error! This was caused by my own code. 
`message=res.json().payload.message;`
You will get this unclear error message if `res.json` or `res.json().payload` doesnt exist.
Just make sure you have a check before the code.
For example:
```
if(res.json && res.json().payload)
        message=res.json().payload.message;
```

**Comment by annayafi** [comment]
Even if you have a problem in your code, it doesn't mean the extension should crash too... imagine visual studio debugger crashing because of a null reference..  
Besides, I had the problem for defined variables too, and I often have to evaluate the crashing variable in the immediate window to see what value is in it, so I guess it's not always related to undefined variable.

**Comment by tvkit** [comment]
Added the `prop.value` conditional test which suppressed the exception.

node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js

```
function propertyPreviewToString(prop) {
    const value = prop.value ? trimProperty(prop.value) : "";
    return prop.type === 'string' ?
        `"${value}"` :
        value;
}
```

**Comment by vladimir-kotikov** [comment]
This is an issue in https://github.com/Microsoft/vscode-chrome-debug-core/blob/24c9c5f47acf889278feb85409bca790caf96fe5/src/chrome/variables.ts#L197 where property value isn't being checked against `null`/`undefined`
