### ISSUE TITLE
Cordova Launch reporting error about GET_LAUNCH_ARGUMENTS

### ISSUE THREAD

**Issue by jcanosa** [Microsoft/vscode-cordova#369]
Been happily developing Cordova apps for weeks now but today it just stopped being able to Launch.  I get the following error immediately:

"[cordova-tools] Error processing "launch": Error: An error occurred while handling message: GET_RUN_ARGUMENTS
    at Socket.<anonymous> (C:\Users\jcanosa\.vscode\extensions\vsmobile.cordova-tools-1.3.3\out\src\common\extensionMessaging.js:51:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)"

Nothing has changed and I get this error in any of the Folder/Projects that had been working.  I have reinstalled both vscode and the extension, but still see the same behavior.  I have tried a couple of different configurations but get the same result with any config.
        {
            "name": "Run android|ios on device|emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
           // "ionicLiveReload": false
        },
        {
            "attachDelay": 1000,
            "name": "Run on Android device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },

I can still build and run the apps from the command line successfully. Any insights and help is much appreciated.

**Comment by jcanosa** [comment]
sorry - just noticed I am no the only one - having the same problem as issue #368
