### ISSUE TITLE
Error launching simulation After updating android platform to 7.0.0

### ISSUE THREAD

**Issue by swindex** [Microsoft/vscode-cordova#386]
## Actual Behavior
1. Launch Simulate Android in Browser throws error: ([cordova-tools] Error processing "launch": Error: Error starting the simulation)

## Expected Behavior
1. Expect it to not throw exception

android platfrom is installed cleanly and is present in platfroms.json and config.xml

## Software versions
- Cordova VS Code extension version: 1.3.8
- VSCode version: 1.21.0
- OS platform and version: win 7
- NodeJS version: latest
- Cordova version: latest
- Cordova-Android version: 7.0.0

## Outputs (Include if relevant)
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
[Extension Host] SIM WARNING: Error starting the simulation
workbench.main.js:sourcemap:257 [Extension Host] SIM ERROR: Project does not include the specified platform: android
	at C:\Users\Eldar\.vscode\extensions\vsmobile.cordova-tools-1.3.8\node_modules\cordova-serve\src\platform.js:45:19
	at _fulfilled (C:\Users\Eldar\.vscode\extensions\vsmobile.cordova-tools-1.3.8\node_modules\q\q.js:854:54)
	at self.promiseDispatch.done (C:\Users\Eldar\.vscode\extensions\vsmobile.cordova-tools-1.3.8\node_modules\q\q.js:883:30)
	at Promise.promise.promiseDispatch (C:\Users\Eldar\.vscode\extensions\vsmobile.cordova-tools-1.3.8\node_modules\q\q.js:816:13)
	at C:\Users\Eldar\.vscode\extensions\vsmobile.cordova-tools-1.3.8\node_modules\q\q.js:877:14
	at runSingle (C:\Users\Eldar\.vscode\extensions\vsmobile.cordova-tools-1.3.8\node_modules\q\q.js:137:13)
	at flush (C:\Users\Eldar\.vscode\extensions\vsmobile.cordova-tools-1.3.8\node_modules\q\q.js:125:13)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)

After rolling back to platform v 6.4.0 it works again

**Comment by annakocheshkova** [comment]
Hi @swindex, thank you for your request. The issue itself appears to be in `cordova-serve` plugin. 
They detect the platform `www` root wrong: in android@7.0 it has moved from `assets/www` to `app/src/main/assets/www`. I suggest you open an issue in their repository.
