### ISSUE TITLE
Simulate Android in browser Debug option not working

### ISSUE THREAD

**Issue by caferosco** [Microsoft/vscode-cordova#397]
## Actual Behavior
Attempt to simulate app, but Visual Studio Code error appears:
[cordova-tools] Error processing "launch": Error: Error starting the simulation at Socket. <anonymous>

## Expected Behavior
Google Chrome should launch showing app simulated in browser with cordova-simulate tools appearing in VSCode.
If "Run Browser" is selected and the browser is added as a platform, browser launches properly.

## Software versions
- Cordova VS Code extension version: 1.3.9
- VSCode version: 1.22.2
- OS platform and version: Windows 10 Education x64 v10.0.16299.402
- NodeJS version: 8.11.1
- Cordova version: 8.0.0
- Cordova-Android/iOS/Windows version: 7.0.0 (also tried 7.1.0)

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching for android (This may take a while)...
An error occurred while attaching to the debugger. Error starting the simulation
Error starting the simulation
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
NO OUTPUT APPEARS
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
workbench.main.js:sourcemap:260 [Extension Host] SIM WARNING: Error starting the simulation
workbench.main.js:sourcemap:260 [Extension Host] SIM ERROR: Project does not include the specified platform: android
	at C:\Users\Student\.vscode\extensions\vsmobile.cordova-tools-1.3.9\node_modules\cordova-serve\src\platform.js:45:19
	at _fulfilled (C:\Users\Student\.vscode\extensions\vsmobile.cordova-tools-1.3.9\node_modules\q\q.js:854:54)
	at self.promiseDispatch.done (C:\Users\Student\.vscode\extensions\vsmobile.cordova-tools-1.3.9\node_modules\q\q.js:883:30)
	at Promise.promise.promiseDispatch (C:\Users\Student\.vscode\extensions\vsmobile.cordova-tools-1.3.9\node_modules\q\q.js:816:13)
	at C:\Users\Student\.vscode\extensions\vsmobile.cordova-tools-1.3.9\node_modules\q\q.js:877:14
	at runSingle (C:\Users\Student\.vscode\extensions\vsmobile.cordova-tools-1.3.9\node_modules\q\q.js:137:13)
	at flush (C:\Users\Student\.vscode\extensions\vsmobile.cordova-tools-1.3.9\node_modules\q\q.js:125:13)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by caferosco** [comment]
UPDATE:  Have opened a ticket with Apache's Cordova team: https://issues.apache.org/jira/browse/CB-14054
