### ISSUE TITLE
Unable to attach to Ionic app running on iOS 12.3.1 real device

### ISSUE THREAD

**Issue by francescodoffizi** [microsoft/vscode-cordova#546]
## Actual Behavior
1. Attach to running iOS on device
2. Output:
Attaching to ios
Configuring debugging proxy
Unable to find target app webview, trying to fallback to the only running webview
Attaching to app.
'Runtime' domain was not foundError processing "attach": 'Runtime' domain was not found: [object Object] or 'Debugger' domain was not foundError processing "attach": 'Debugger' domain was not found: [object Object]

## Expected Behavior
1. Attach to running iOS on device
2. Debugger working

## Software versions
Latest stable

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):

Attaching to ios
Configuring debugging proxy
Unable to find target app webview, trying to fallback to the only running webview
Attaching to app.
'Debugger' domain was not foundError processing "attach": 'Debugger' domain was not found: [object Object]

- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
No Cordova entry in listbox

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```js
workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'hash' of null
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3215
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:238 [Extension Host] stack trace: TypeError: Cannot read property 'hash' of null
	at BlameViewProvider.<anonymous> (/Users/francescodoffizi/.vscode/extensions/huizhou.githd-2.1.0/out/src/blameViewProvider.js:178:29)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/francescodoffizi/.vscode/extensions/huizhou.githd-2.1.0/out/src/blameViewProvider.js:4:58)
	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3215
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:3241 [[object Object]]Cannot read property 'hash' of null
$onExtensionRuntimeError @ workbench.main.js:3241
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:3241 TypeError: Cannot read property 'hash' of null
	at BlameViewProvider.<anonymous> (/Users/francescodoffizi/.vscode/extensions/huizhou.githd-2.1.0/out/src/blameViewProvider.js:178)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/francescodoffizi/.vscode/extensions/huizhou.githd-2.1.0/out/src/blameViewProvider.js:4)
	at process._tickCallback (internal/process/next_tick.js:68)
$onExtensionRuntimeError @ workbench.main.js:3241
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```

**Comment by SounD120** [comment]
Hi @francescodoffizi and thanks for reaching us. Could you please describe your specific software versions? This information will be very helpful for us. Also could you please clarify what kind of application do you use: Cordova or Ionic? Also it will be helpful if you add information about iOS version that installed on your device.
You can use the following template:
```
## Software versions
- Cordova VS Code extension version:
- VSCode version:
- OS platform and version:
- NodeJS version:
- Cordova version:
- Cordova-Android/iOS/Windows version:
```

**Comment by francescodoffizi** [comment]
Ionic projects (3 or 4 makes no difference as far as I can see)
Cordova 8.1.2 (cordova-lib@8.1.1)
VSCode: Versione 1.35.1 (1.35.1)
MacOS: 10.14.5 (18F132)
Node: v10.14.2
Cordova Tools: 1.8.3
iOS: 12.3.1

**Comment by francescodoffizi** [comment]
@SounD120 I did a test with a older Ionic 3.2 app and it works... so maybe the issue is ionic 4 related...

**Comment by ruslan-bikkinin** [comment]
@francescodoffizi looks like this is Ionic bug, because I couldn't even inspect Ionic app using Chrome. I've created [an issue](https://github.com/ionic-team/ionic/issues/18733) in Ionic tracker, so, I'd suggest you to subscribe to it to be posted as to it.
