### ISSUE TITLE
Error: Set breakpoints request timed out

### ISSUE THREAD

**Issue by ntgpsn** [microsoft/vscode-cordova#551]
## Actual Behavior
debug on andriod device , error like this :
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (c:\Users\Administrator\.vscode\extensions\msjsdiag.cordova-tools-1.8.3\node_modules\vscode-chrome-debug-core\out\src\utils.js:96:24)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)

## Outputs (Include if relevant)
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (c:\Users\Administrator\.vscode\extensions\msjsdiag.cordova-tools-1.8.3\node_modules\vscode-chrome-debug-core\out\src\utils.js:96:24)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)

someone has this problem?

**Comment by ruslan-bikkinin** [comment]
Hi @ntgpsn and sorry for delayed response. Could you please fill [issue template](https://github.com/microsoft/vscode-cordova/blob/master/.github/ISSUE_TEMPLATE.md) so we could get more details about your specific case?

**Comment by ruslan-bikkinin** [comment]
@ntgpsn do you have a chance to look at this?

**Comment by SounD120** [comment]
Hi @ntgpsn . I'm closing this due to inactivity. Please feel free to reopen if needed.
