### ISSUE TITLE
Enviroment paths are not taken into account.

### ISSUE THREAD

**Issue by Hadatko** [microsoft/vscode-cordova#590]
## Actual Behavior
1. In Visual Studio Code terminal i see correct enviroment paths for Android SDK
2.In Visual Studio Code debug  i see wrong default enviroments paths for Android SDK -> cause build tools not found error

## Expected Behavior
1. Take enviroment variables from system

## Software versions
- Cordova VS Code extension version: 1.9.0
- VSCode version:1.40.2
- OS platform and version: Kubuntu 19.10
- NodeJS version: 11.15.0
- Cordova version: 9.0.0
- Cordova-Android/iOS/Windows version: android@8

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching for android (This may take a while)...
Warning: Ionic live reload is currently only supported for Ionic 1 projects. Continuing deployment without Ionic live reload...
No scripts found for hook "before_run".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
PlatformApi successfully found for platform android
Checking for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at /home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/app/src/main/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
[Gradle Properties] Appending default configuration properties
[Gradle Properties] Appending custom configuration properties
[Gradle Properties] Updating and Saving File
Merging and updating files from [www, platforms/android/platform_www] to platforms/android/app/src/main/assets/www
Wrote out android application name "HelloCordova" to /home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/app/src/main/res/values/strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
Wrote out Android package name "com.ozm.daqAndroidDevice" to /home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/app/src/main/java/com/ozm/daqAndroidDevice/MainActivity.java
This app does not have launcher icons defined
This app does not have splash screens defined
This app does not have additional resource files defined
Prepared android project successfully
No scripts found for hook "after_prepare".
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/usr/lib/android-sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
Running command: /home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/gradlew cdvBuildDebug -b /home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/build.gradle

> Configure project :app
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '/home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/CordovaLib/cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':app'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Command finished with error code 1: /home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/gradlew cdvBuildDebug,-b,/home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/build.gradle
/home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '/home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/CordovaLib/cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':app'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Error: /home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '/home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/platforms/android/CordovaLib/cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':app'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
    at ChildProcess.whenDone (/home/kuhadatko/kseftiky/daq-ozm/daq-ozm/gui/android/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
'cordova run android --device --verbose --no-update-notifier' failed with exit code 1

```
- Visual Studio Code Terminal Output:
```
kuhadatko@kuhadatko-GL552VW:~/kseftiky/daq-ozm/daq-ozm/gui/android$ echo ${ANDROID_SDK_ROOT}
/home/kuhadatko/Android/Sdk
kuhadatko@kuhadatko-GL552VW:~/kseftiky/daq-ozm/daq-ozm/gui/android$ echo ${ANDROID_HOME}
/home/kuhadatko/Android/Sdk
```

**Comment by RedMickey** [comment]
Hi @Hadatko and thanks for your reporting. As seen from your logs there may be two different `ANDROID_HOME` system variable definitions in `~/.bashrc` and  `~/.bash_profile`. VS Code editor launched from UI requires system variables to be defined in `~/.bash_profile`. Please make sure that your `~/.bash_profile` file contains correct environment variables.

**Comment by Hadatko** [comment]
Hi @RedMickey,
unfortunatelly i don't have .bash_profile at all.

**Comment by Hadatko** [comment]
It looks like newer OS doesn't have .bash_profile file. Are you parsing this file? Is it wise? Shouldn't you read system environment variables from system itself?

**Comment by RedMickey** [comment]
@Hadatko, the extension doesn't parse any environment variables itself. It uses the environment variables that VS Code editor provides to it. 
If there isn't `~/.bash_profile` file in your system, please make sure that `~/.profile` file refers to `~/.bashrc` and `~/.bashrc` contains all the environment settings. 

`~/.profile` should contain something like this to forward all settings from `~/.bashrc` :
```
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
```

Please add the code above to `~/.profile` file if there isn't.
1. Run `nano ~/.profile`
1. Add the code above and save the changes
1. Rub `source ~/.profile`
1. Restart VS Code editor

Also you can start VS Code from system terminal by using `code` command. So the editor will take variables from `~/.bashrc` file.

Could you please try these suggestions and let us know about your results?

**Comment by Hadatko** [comment]
I am always running code from cmd. But i need to tell that today it is working. Maybe restart system helped (i don't know how. I restarted app several times with new terminal with actual enviroment as described above.). I also don't have .profile file. But it started work so i am fine. Thank you for your time and help ;)

**Comment by RedMickey** [comment]
Sounds good! Please feel free to open new ones if needed.

**Comment by Windstalker** [comment]
@RedMickey I am using zsh isntead of bash and I have the same issue. What should I do in my case?

**Comment by RedMickey** [comment]
Hi @Windstalker, I tried to use `zsh` instead of `bash` and didn't face any problems. I configured `zsh` the following way:
1. Download `zsh` and set it as default
1. Add NVM configuration to `~/.zshrc`
    ```
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    ```
1. Run `source ~/.zshrc` in terminal

After that VS Code should also use `zsh` as default terminal.
