### ISSUE TITLE
Unable to find 'localabstract' name of Cordova app (error code 406)

### ISSUE THREAD

**Issue by si458** [microsoft/vscode-cordova#904]
## Actual Behavior
1. launches simulator as expected
2. even launches the sample app as expected
3. shows error in Debug console `Unable to find 'localabstract' name of Cordova app (error code 406)` but never shows any debug information

## Expected Behavior
1. to attach to the emulator and show debugging info

## Software versions
- Cordova VS Code extension version: 2.6.4
- VSCode version: 1.81.0
- OS platform and version: Windows 11 Pro
- NodeJS version: 18.17.0
- Cordova version: 12.0.0
- Cordova-Android/iOS/Windows version: cordova-android@12.0.0
- Android 13 - SDK 33 - Java 11.0.20

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching for android (This may take a while)...
Checking Java JDK and Android SDK versions
ANDROID_HOME=C:\Users\sas_2\AppData\Local\Android\Sdk (recommended setting)
ANDROID_SDK_ROOT=undefined (DEPRECATED)
Using Android SDK: C:\Users\sas_2\AppData\Local\Android\Sdk
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript UP-TO-DATE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :CordovaLib:extractDeepLinksDebug UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :CordovaLib:compileDebugLibraryResources UP-TO-DATE
> Task :CordovaLib:parseDebugLocalResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:bundleLibCompileToJarDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders UP-TO-DATE
> Task :CordovaLib:compileDebugShaders NO-SOURCE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:processDebugJavaRes UP-TO-DATE
> Task :CordovaLib:bundleLibResDebug UP-TO-DATE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :CordovaLib:bundleLibRuntimeToDirDebug UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeProjectDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:mergeDebugNativeLibs NO-SOURCE
> Task :CordovaLib:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :app:mergeDebugNativeLibs NO-SOURCE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:createDebugApkListingFileRedirect UP-TO-DATE
> Task :app:assembleDebug UP-TO-DATE
> Task :app:cdvBuildDebug UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5s
50 actionable tasks: 50 up-to-date
Built the following apk(s): 
	C:\Users\sas_2\Documents\Developer\cordova\ultimatewarrior\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_HOME=C:\Users\sas_2\AppData\Local\Android\Sdk (recommended setting)
ANDROID_SDK_ROOT=undefined (DEPRECATED)
Using Android SDK: C:\Users\sas_2\AppData\Local\Android\Sdk
Deploying to emulator emulator-5554
.
.
.
.
.
Using apk: C:\Users\sas_2\Documents\Developer\cordova\ultimatewarrior\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Package name: com.hestor.ultimatewarrior
INSTALL SUCCESS
LAUNCH SUCCESS
Attaching to android
Unable to find 'localabstract' name of Cordova app (error code 406)
Unable to find 'localabstract' name of Cordova app (error code 406)
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
Launched emulator S23_API_33
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

p @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

	at o.getNestedError (c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:435292)
	at c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:442992
	at ChildProcess.exithandler (node:child_process:417:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
p @ console.ts:137
mainThreadExtensionService.ts:81 [msjsdiag.cordova-tools]Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

	at o.getNestedError (c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:435292)
	at c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:442992
	at ChildProcess.exithandler (node:child_process:417:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

p @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

	at o.getNestedError (c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:435292)
	at c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:442992
	at ChildProcess.exithandler (node:child_process:417:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
p @ console.ts:137
mainThreadExtensionService.ts:81 [msjsdiag.cordova-tools]Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

	at o.getNestedError (c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:435292)
	at c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:442992
	at ChildProcess.exithandler (node:child_process:417:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
5console.ts:137 [Extension Host] Sundial will apply your night theme! 🌑
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

p @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

	at o.getNestedError (c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:435292)
	at c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:442992
	at ChildProcess.exithandler (node:child_process:417:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
p @ console.ts:137
mainThreadExtensionService.ts:81 [msjsdiag.cordova-tools]Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error: Error while executing command 'adb -s "emulator-5554" forward --remove tcp:9222': Command failed: adb -s "emulator-5554" forward --remove tcp:9222
adb.exe: error: listener 'tcp:9222' not found

	at o.getNestedError (c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:435292)
	at c:\Users\sas_2\.vscode\extensions\msjsdiag.cordova-tools-2.6.4\dist\cordova-extension.js:4:442992
	at ChildProcess.exithandler (node:child_process:417:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by EzioLi01** [comment]
Hey @si458 , thanks for reaching us. This related to AndroidManifest.xml changes on cordova-android@12.0.0, we're working on fixing. Will let you know if it's fixed. Thank you!

**Comment by EzioLi01** [comment]
This issue should be fixed on above PR and will release in next version, you can use cordova-android <= 12.0.0 for your project temporarily.

**Comment by si458** [comment]
> This issue should be fixed on above PR and will release in next version, you can use cordova-android <= 12.0.0 for your project temporarily or build the latest .vsix file to install locally.

Thanks! Any idea of when the next release will be?

**Comment by EzioLi01** [comment]
> > This issue should be fixed on above PR and will release in next version, you can use cordova-android <= 12.0.0 for your project temporarily or build the latest .vsix file to install locally.
> 
> Thanks! Any idea of when the next release will be?

Plan to start V2.6.5 release process in next week.

**Comment by EzioLi01** [comment]
Cordova-tools V2.6.5 is released. This issue should be fixed on this version.

**Comment by si458** [comment]
thanks @EzioLi01 works a treat now!
my poor old macbook pro 2012 is slow as hell tho haha
