### ISSUE TITLE
Spawn EINVAL

### ISSUE THREAD

**Issue by Covarians** [microsoft/vscode-cordova#985]
## Actual Behavior
When trying to debug a cordova app, the debugger gets stucked on 
Your cordova-android version is 12, reqiured target sdk 33 and build-tools 33.0.2.
Launching for android (This may take a while)...
spawn EINVAL
## Expected Behavior
Normal debugging and application start

## Software versions
- Cordova VS Code extension version:  2.7.0
- VSCode version: 1.92.2
- OS platform and version: Windows 11 23H2
- NodeJS version: 18.17.1
- Cordova version: 12.0.0
- Cordova-Android/iOS/Windows version: Android 12.0.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
our cordova-android version is 12, reqiured target sdk 33 and build-tools 33.0.2.
Launching for android (This may take a while)...
spawn EINVAL
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
Activating task providers java

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
  ERR [Extension Host] Error while detecting Ionic CLI version TypeError: Cannot read properties of null (reading 'toString')
    at Function.getIonicCliVersion (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:527569)
    at Function.isIonicCliVersionGte (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:527659)
    at new f (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:533857)
    at F.<anonymous> (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:450534)
    at Generator.next (<anonymous>)
    at s (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:441086)
console.ts:137 [Extension Host] Error while detecting Ionic CLI version TypeError: Cannot read properties of null (reading 'toString')
    at Function.getIonicCliVersion (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:527569)
    at Function.isIonicCliVersionGte (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:527659)
    at new f (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:533857)
    at F.<anonymous> (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:450534)
    at Generator.next (<anonymous>)
    at s (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:441086)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Error while executing command 'adb -s "192.168.1.107:5555" forward --remove tcp:5555': Command failed: adb -s "192.168.1.107:5555" forward --remove tcp:5555
adb.exe: error: listener 'tcp:5555' not found

y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: Error: Error while executing command 'adb -s "192.168.1.107:5555" forward --remove tcp:5555': Command failed: adb -s "192.168.1.107:5555" forward --remove tcp:5555
adb.exe: error: listener 'tcp:5555' not found

    at Function.getNestedError (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:407832)
    at c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:415532
    at ChildProcess.exithandler (node:child_process:431:5)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:78 [msjsdiag.cordova-tools]Error while executing command 'adb -s "192.168.1.107:5555" forward --remove tcp:5555': Command failed: adb -s "192.168.1.107:5555" forward --remove tcp:5555
adb.exe: error: listener 'tcp:5555' not found

$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 Error: Error while executing command 'adb -s "192.168.1.107:5555" forward --remove tcp:5555': Command failed: adb -s "192.168.1.107:5555" forward --remove tcp:5555
adb.exe: error: listener 'tcp:5555' not found

    at Function.getNestedError (c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:407832)
    at c:\Users\dirte\.vscode\extensions\msjsdiag.cordova-tools-2.7.0\dist\cordova-extension.js:4:415532
    at ChildProcess.exithandler (node:child_process:431:5)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
```

**Comment by lexie011** [comment]
Hey @Covarians, could you please uninstall existing extension and try on this one (Unzip and manually install .vsix file in vscode extension tab)? Any issue please let me know.
[cordova-tools-2.7.0.vsix.zip](https://github.com/user-attachments/files/16688975/cordova-tools-2.7.0.vsix.zip)

**Comment by EzioLi01** [comment]
Related to #979.

**Comment by lexie011** [comment]
@Covarians Please use this extension for now, once Microsoft pipeline finish updating, we will work on a new version release.
